site_name: foReal Documentation
theme: readthedocs
nav:
  - index.md
  - get_started.md
  - concept.md
  - examples.md
  - api.md

repo_url: https://github.com/niowniow/foreal

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js